### ISSUE TITLE
Seems HostMetaApiService does not work for method (topic) registration

### ISSUE THREAD

**Issue by nj4x** [Code-Sharp/WampSharp#110]
Hello, Elad.

Please use this gist: https://gist.github.com/nj4x/dab94f833ca1e973623b to reproduce my case.

(WampSharp 1.2.4.111-dev)

**Comment by darkl** [comment]
Hi Roman,

This seems to work fine with Json serialization but doesn't work with msgpack serialization. I think it is related to the way I serialize DateTime in Newtonsoft.Msgpack.

I will try to investigate this further during the weekend.

Elad

**Comment by darkl** [comment]
Ok - the problem is Newtonsoft.Msgpack serializes DateTime as a number (like msgpack-cli does) and after that WampSharp deserializes the object first into a JToken and later to a RegistrationDetails, but now JTokenReader occurs a number it doesn't attempt to convert it into a DateTime.

It seems that crossbar sends DateTime as a string, which is less compact but seems more compatible (other WAMP implementations might not know how to convert a number to a DateTime). I guess we should add an option to Newtonsoft.Msgpack MessagePackReader to write DateTime as string and use it in WampSharp.

Elad

**Comment by nj4x** [comment]
Ok, I've removed MsgpackSerialization from that example and put JsonSerialization instead. Now it does not work when using RawSocketTransport instead of WebSocketTransport: https://gist.github.com/nj4x/92c118ed9ca57461755a

**Comment by darkl** [comment]
Hi,

I'm not sure why the router doesn't detect the client disconnection. Adding auto-pings eventually fixes this. (Set the auto-ping interval of

**Comment by nj4x** [comment]
Added AutoPing(TimeSpan.FromSeconds(2)) - did not help. Subsequent RPC registrations also does not work:

**Comment by darkl** [comment]
Yeah, that's because you need to add to router side (so the router will detect disconnection):

```csharp
defaultWampHost.RegisterTransport(new RawSocketTransport(new TcpListener(8090), autoPingInterval: TimeSpan.FromSeconds(20)), new JTokenJsonBinding(), new JTokenMsgpackBinding());
```

**Comment by darkl** [comment]
Ok, got it - ReadAsync returns 0 if the end of the stream has been reached. Will try to fix this.

**Comment by darkl** [comment]
Hi Roman,

Just released a new version to MyGet with a fix. Should work also without auto-pings :)

Elad

**Comment by nj4x** [comment]
Thanks, Elad.

MetaApiService works on RawSocketTransport/JsonSerialization now.

**Comment by darkl** [comment]
Hi Roman,
I released today a version of Newtonsoft.Msgpack with a fix, and a version of WampSharp to MyGet feed. Should work now also with MsgPack serialization.

Elad

**Comment by nj4x** [comment]
Thank you very much, Elad.
It works like expected.
