### ISSUE TITLE
Requires version 7.0.0.0 of Newtonsoft.Json that does not exist

### ISSUE THREAD

**Issue by darkpixel** [Code-Sharp/WampSharp#117]
```
An unhandled exception of type 'System.InvalidOperationException' occurred

Additional information: An error occurred creating the form. See Exception.InnerException for details.  The error is: Could not load file or assembly 'Newtonsoft.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
```

Newtonsoft.Json jumps from 6.0.8 to 7.0.1 in NuGet.

**Comment by darkl** [comment]
Hi @darkpixel,

What IDE/Package manager are you using? The package requires Newtonsoft.Json between 6.0.5 to 7.0 (see also in [NuGet Gallery](http://www.nuget.org/packages/WampSharp.NewtonsoftJson/1.2.3.14-beta))

It seems like a bug in your package manager. (Works for me fine in Visual Studio 2015)

Anyways, you can just remove the polluted assembly bindings from your app.config in order to resolve this issue locally.

Elad

**Comment by darkpixel** [comment]
Visual Studio 2015 Community Edition.

I found the lines in app.config and removed it.  That fixed the issue.

Thanks for your help.  I've been writing software under Linux for ~15 years and this is my first attempt at a small Windows app.  ;)
