### ISSUE TITLE
Blacklisting and whitelisting using authroles

### ISSUE THREAD

**Issue by esso23** [Code-Sharp/WampSharp#119]
When I'm publishing an event I cannot black/white-list using authroles.
According to specification (13.4.1.), PublishOptions should contain attributes to do this.
 "PUBLISH.Options.exclude_authrole|list[string]"
 "PUBLISH.Options.eligible_authrole|list[string]"
Same goes for authid.
Currently I can only pass array of longs (SessionIds).

Also, "authrole|string" seems to be missing in your implementation of Session Meta Api in "wamp.session.on_join" (spec 13.7.1.2.1.) (although "authid|string" is present).

Any plans on implementing this?
Thaks a lot
Esso

**Comment by darkl** [comment]
Hi Esso,

Thanks for opening this issue.

Regarding the auth_role/auth_id based black/white listing - the spec indeed specifies this feature, but practically no WAMP router implements it nowadays. Note that it is a relatively new feature. It would probably be implemented in a future release, but I prefer to wait till it is implemented in Crossbar, since the spec is likely to change.

Regarding the authrole issue - this is actually a bug - do you mind opening a separate issue for it? Thanks.

Best regards,
Elad

**Comment by darkl** [comment]
Implemented in v1.2.6.41-beta.
