### ISSUE TITLE
WampSharp + Unity

### ISSUE THREAD

**Issue by TarasOsiris** [Code-Sharp/WampSharp#123]
Did anyone test it on Unity? Will it work in Unity? If yes, what are platform limitations?

**Comment by darkl** [comment]
Hi @TarasOsiris,

I didn't try to test the library on Unity, but it seems that it won't be simple to make it work - the library relays heavily on Tasks and on Reactive Extensions, and it seems that Unity is stuck in CLR 2.0.

A port might be possible - using some libraries might help:
* [Unity C# 5.0 and 6.0 Integration](https://bitbucket.org/alexzzzz/unity-c-5.0-and-6.0-integration/overview)
* [UniRx](https://github.com/neuecc/UniRx)

But I'm not currently interested in working on such port. If you (or someone else) are willing to work on such port, I'll try to make my best in order to merge it to master.

Best regards,
Elad

**Comment by mvapetrovic** [comment]
Hi @TarasOsiris,

did you figure out a way to use WampSharp and Unity?
I am having the same problem here and even when using darkl's suggestion to integrate C# 5.0 and 6.0 I still get the following error in Unity:

"Assets\CSharp 6.0 Support\AsyncTools\UnityTaskScheduler.cs(32,11): error CS7069: Reference to type 'Task<>' claims it is defined in 'mscorlib', but it could not be found"

Does anybody have a solution?

Best regards,
Alex

**Comment by TarasOsiris** [comment]
@mvapetrovic Hey, no I didn't. 

Didn't have time to investigate but looks like it's not that simple. Unity uses CLR 2.0 so probably error is that it uses something that is not there. I think there is much more porting effort needed.

**Comment by darkl** [comment]
Won't fix.
