### ISSUE TITLE
WampSharp.V2.Core.Contracts.WampConnectionBrokenException

### ISSUE THREAD

**Issue by LordMandrake** [Code-Sharp/WampSharp#124]
Hi, I'm trying to do this:

    if (Channel.RealmProxy.Monitor.IsConnected)
        Channel.Close("Manual Shutdown", new GoodbyeDetails());

And recieve this:

> WampSharp.V2.Core.Contracts.WampConnectionBrokenException was unhandled
> Message: An unhandled exception of type 'WampSharp.V2.Core.Contracts.WampConnectionBrokenException' occurred in mscorlib.dll
> Additional information: Connection got broken. CloseType:Disconnection

I have declared event handlers:

    Channel.RealmProxy.Monitor.ConnectionBroken += CbMonitor_ConnectionBroken;
    Channel.RealmProxy.Monitor.ConnectionError += CbMonitor_ConnectionError;
    Channel.RealmProxy.Monitor.ConnectionEstablished += CbMonitor_ConnectionEstablished;

Could any help me ???

**Comment by darkl** [comment]
Hi Gustavo,

I tried closing the channel manual as used demonstrated, but I got no error.

I guess your code is a bit more complicated and involves other things such
as Rpc calls or Pub/Sub. Anyways, once the connection is lost, no matter if
you intended it or not, all your pending rpc calls and subscriptions notify
the application about it. In order to prevent it, you should cancel all
your registrations/subscriptions before disconnecting.

Regards
Elad

**Comment by shaijujanardhanan** [comment]
Hi,
I am facing the same issue with closing the channel. 
Could you please tell me how to cancel the subscriptions ?

**Comment by shaijujanardhanan** [comment]
Hi 
Just an update ..I am not receiving the issue if i dispose off the subscription before the channel is closed

Thanks
Shaiju

**Comment by darkl** [comment]
When you subscribe to a topic, you get a disposable. Call Dispose before
closing the channel.

Elad
