### ISSUE TITLE
Awaiting channel.Open() somehow prevents Rx subscriptions from getting called.

### ISSUE THREAD

**Issue by georgiosd** [Code-Sharp/WampSharp#138]
This makes no sense to me but hopefully it will to someone else. 

In the Rx sample, the channel is opened via `channel.Open.Wait()` which works fine.

If you switch that up to `await channel.Open()` it will still appear to work but the subscriptions will never receive any callbacks (breakpoints never hit).

Any ideas?

**Comment by darkl** [comment]
Hi,

I changed the samples in [this page](https://github.com/Code-Sharp/WampSharp-docs/blob/master/WAMP2/Roles/Subscriber/Rx-based-Subscriber.md) to use async/await. Basically, the problem was that when awaiting channel.Open, you return to the WebSocket thread, and therefore calling Console.ReadLine() line blocks this thread from reading further messages from the WebSocket.

Elad

**Comment by georgiosd** [comment]
Ah yes, the infamous `ConfigureAwait()`... thanks!
