### ISSUE TITLE
Disconnection detecting 

### ISSUE THREAD

**Issue by thelloworldt** [Code-Sharp/WampSharp#246]
Hello!
Is there any way to detect disconnection from realm on the router side? As I noticed there are SessionCreated method and SessionClosed, but SessionClosed, but it occurs only after timeout (when a connection was not closed properly, without GoodBye message). So how can I handle this case to detect immediately when SessionClosed ?
Thanks

**Comment by darkl** [comment]
Hi,
The thing is that since the session disconnected improperly, it didn't send a FIN packet. In order to detect this, the router periodically sends a ping message to all sessions (I think every minute). The first time it detects that the session is gone, is when this event handler is raised. We can try to make the ping interval configurable (this is already possible for instance for the vtortola transport for instance), but you will still have some delay. One can make the ping interval very small, but this has the trade-off of sending much more messages per minute.

**Comment by darkl** [comment]
You can solve this kind of issue using RegisterOptions, specifying RegisterOptions.Invoke = WampInvokePolicy.Last.

Elad

**Comment by thelloworldt** [comment]
Thanks a lot!
