### ISSUE TITLE
Dropping frameworks support

### ISSUE THREAD

**Issue by darkl** [Code-Sharp/WampSharp#252]
Currently WampSharp supports the following .NET framework variants (each has its own solution file):

- .NET Framework 4.5
- .NET Framework 4.0
- .NET Standard 1.3
- .NET Standard 2.0
- Universal Windows Platform
- Portable Class Libraries (but mainly Windows Phone 8.1)

I also have a patch solution for Xamarin (it is a fallback to System.Reflection.DispatchProxy, since Castle.Core isn't available for Xamarin.iOS).

The way all these platforms are currently supported is not ideal and requires a lot of maintenance. Furthermore, some of WampSharp's dependencies have already dropped support for these frameworks. The most important dependency to consider is Reactive Extensions, which for a long time does not support .NET Framework 4.0, and since [last week](https://github.com/dotnet/reactive/commit/0f9ce1906fa81c89ad2acbdf0df2112782fdb712) does not support .NET Framework 4.5, .NET Standard 1.3 and Portable Class Libraries anymore.

There is [some discussion](https://twitter.com/Nick_Craver/status/1001272947032711168) going on these days, suggesting to drop support for .NET Standard < 2.0.

I would like to drop support for most of these platforms and leave support only for .NET Standard 2.0 and maybe UWP (and a patch for Xamarin and platforms that don't support System.Reflection.Emit.ILGeneration).

This won't happen in the upcoming version, but will happen in a couple versions after that. If you need support for any platform which is not supported by .NET Standard 2.0 or UWP, please reply here and explain why. Please note that .NET Framework 4.0 and .NET Framework 4.5 are deprecated [for a couple of years](https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/) already, but still reply if you need support for these, with an explanation.

Thanks
Elad

**Comment by StevenBonePgh** [comment]
I have been prototyping a solution using Xamarin.Forms 3.0 on Android and UWP, and have not had any issues with WampSharp (using CRA and RPC, no publish/subscribe features).  It seems to follow .NET Standard 2.0 pretty close, although on Android (at least) it runs under Mono.  I have seen some things in a .NET Standard 2.0 application that throw NotImplementedExceptions (like Named Mutexes) running in the Xamarin/Android space.  Other than iOS, is there a specific known scenario where WampSharp fails?

As for supported frameworks, as per Microsoft: 
> Support for .NET 4.5.2 follows the lifecycle policy of the parent operating system. It is supported as a Windows component on the latest required operating system update for Windows Vista SP2, Windows 7 SP1, Windows Server 2008 SP2, Windows Server 2008 R2 SP1, Windows 8.1 Update, Windows Server 2012, and Windows Server 2012 R2.

We have an application that requires PA-DSS validation. Although we are not using WampSharp to handle cardholder data, we do utilize it for some additional functionality. As per some discussions with the folks that perform the validations, changing the version of the .NET Framework is something that can be done only with a revalidation (other people tell me it does not matter).  In my case, this is about a year out before I can upgrade.  While one person's situation shouldn't influence direction, I'd prefer to keep .NET 4.5.2 for the time being.  On the other hand, Reactive dropping .NET 4.5.2 is a compelling argument for removal.  Due to the stability of WampSharp and the protocol itself, dropping support shouldn't be a huge deal.  The architecture also makes it somewhat easy to replace some components should the need arise.

**Comment by darkl** [comment]
Half an year has past, and expect for @StevenBonePgh no one replied.
I plan to discontinue support for all platforms expect .NET Standard 2.0, UWP, a special patch for Xamarin.iOS, and probably .NET Framework 4.6.1 (see [this tweet](https://twitter.com/terrajobst/status/1031999730320986112?lang=en)). This should is likely to happen in June 2019.
Please answer the above questions if they apply to you.

Thanks
Elad

**Comment by esso23** [comment]
We currently have our entire code base on .NET 4.6.1 (we dropped .NET 4 [Win Server 2003] and .NET 4.5 support ~6 months ago), with a few .NET Standard 2.0 libraries. I have plans to migrate everything to .NET 4.7.2 sometime next year (our limiting factor is support for Windows Server 2008 R2, which *should* support .NET 4.7.2 just fine). So if you decide to drop .NET 4.6.1 support, we're gonna be fine, the only thing we really need is .NET Standard 2.0.

Thank you
Esso

**Comment by darkl** [comment]
@NichUK of course you would be able to use earlier WampSharp versions that do target .NET Framework 4.0. The only problem is that these won't receive hotfixes anymore. WampSharp is considered to be stable so this hopefully should not be a problem.

**Comment by darkl** [comment]
Hi,

There is currently a inconsistency with the package `WampSharp.Default.Client`. On `netstandard` platforms it uses `WampSharp.WebSockets` and on `net40`/`net45`/`net46` it uses `WampSharp.WebSocket4Net`. The reason for this is because when I first ported WampSharp to `netstandard1.3`, there was no `WebSocket4Net` support for `netstandard1.3`.

Since I'm dropping support for all platforms except for `net461`, `netstandard2.0`, `netstandard2.1`, `Xamarin.iOS` and `uap`, I as thinking of solving this inconsistency. I think I will make `WampSharp.Default.Client` use `WampSharp.WebSockets` everywhere except for `uap` (where we will use `WampSharp.Windows`).

This should not be a problem, as one can always install `WampSharp.WebSocket4Net` and `WampSharp.NewtonsoftJson` separately and use the fluent syntax api (which in my opinion is a better api).

Elad

**Comment by darkl** [comment]
Also I'm planning to drop support for `WampSharp.SignalR`. This is not really documented and I doubt anyone uses it.

Elad

**Comment by darkl** [comment]
Superseded by #303.
