### ISSUE TITLE
Xamarin iOS Compile Issue

### ISSUE THREAD

**Issue by jaimewyant** [Code-Sharp/WampSharp#256]
I create a default Xamarin.Forms app in Visual Studio for Mac.

My nuget packages are:
```
WampSharp 18.6.1
WampSharp.Default.Client 18.6.1
Xamarin.Forms 3.0.0.482510
```

SDK
```.net standard 2.0.1```

When I compile I get this error:

> /Users/jaimewyant/Projects/TestApp/TestApp.iOS/MTOUCH: Error MT0034: Cannot reference 'monotouch.dll' in a Xamarin.iOS project - it is implicitly referenced by 'MsgPack, Version=0.7.0.0, Culture=neutral, PublicKeyToken=a2625990d5dc0167'. (MT0034) (TestApp.iOS)

Is there a way around this?  I don't even use MsgPack, but I'm not sure how to throw together a package like Default.Client that excludes MsgPack.

**Comment by darkl** [comment]
Can you please try to remove the WampSharp.Default.Client reference and add
WampSharp.WebSockets and WampSharp.NewtonsoftJson references and use fluent
syntax api instead?

Elad

On Jun 29, 2018 19:01, "Jaime Wyant" <notifications@github.com> wrote:

I create a default Xamarin.Forms app in Visual Studio for Mac.

My nuget packages are:

WampSharp 18.6.1
WampSharp.Default.Client 18.6.1
Xamarin.Forms 3.0.0.482510

SDK
.net standard 2.0.1

When I compile I get this error:

/Users/jaimewyant/Projects/TestApp/TestApp.iOS/MTOUCH: Error MT0034: Cannot
reference 'monotouch.dll' in a Xamarin.iOS project - it is implicitly
referenced by 'MsgPack, Version=0.7.0.0, Culture=neutral,
PublicKeyToken=a2625990d5dc0167'. (MT0034) (TestApp.iOS)

Is there a way around this? I don't even use MsgPack, but I'm not sure how
to throw together a package like Default.Client that excludes MsgPack.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Code-Sharp/WampSharp/issues/256>, or mute the thread

**Comment by jaimewyant** [comment]
@darkl that fixed things (and I like the fluent syntax better also).  It is a double win, thanks!
