### ISSUE TITLE
wamp.error.invalid_argument

### ISSUE THREAD

**Issue by esso23** [Code-Sharp/WampSharp#261]
Hi Elad,

I'm calling an RPC with this signature:
```cs
        [WampProcedure("publish_multiple_d2_objects")]
        void PublishMultipleD2Objects(string mask, D2ObjectTypeDTO objectType);
```
(D2ObjectTypeDTO is an enum)

and I'm getting this error (on callee):

```
...
DEBUG|WampSharp.Msgpack.MessagePackParser|Parsed msgpack message: "[48,1026659629621231,{},"sk.ipecon.development.d2client.publish_multiple_d2_objects",["*",3]]"
DEBUG|WampSharp.Core.Dispatch.WampIncomingMessageHandler`2[Newtonsoft.Json.Linq.JToken,WampSharp.V2.Core.Contracts.IWampClientProxy`1[Newtonsoft.Json.Linq.JToken]]|Mapped message to method: Void Call(WampSharp.V2.Core.Contracts.IWampCaller, Int64, WampSharp.V2.Core.Contracts.CallOptions, System.String, Newtonsoft.Json.Linq.JToken[])
DEBUG|WampSharp.Core.Proxy.WampOutgoingRequestSerializer`1[System.Object]|Calling remote peer proxy method: Void Invocation(Int64, Int64, WampSharp.V2.Core.Contracts.InvocationDetails, System.Object[])
DEBUG|WampSharp.Core.Dispatch.WampIncomingMessageHandler`2[System.Object,System.Object]|Mapped message to method: Void Invocation(Int64, Int64, WampSharp.V2.Core.Contracts.InvocationDetails, System.Object[])

ERROR|WampSharp.V2.Rpc.LocalRpcOperation.sk.ipecon.development.d2client.publish_multiple_d2_objects|An error occured while calling "sk.ipecon.development.d2client.publish_multiple_d2_objects"

DEBUG|WampSharp.Core.Proxy.WampOutgoingRequestSerializer`1[System.Object]|Calling remote peer proxy method: Void Error(Int32, Int64, System.Object, System.String, System.Object[])
DEBUG|WampSharp.Core.Dispatch.WampIncomingMessageHandler`2[System.Object,WampSharp.V2.Core.Contracts.IWampClientProxy`1[System.Object]]|Mapped message to method: Void Error(WampSharp.V2.Core.Contracts.IWampClientProxy, Int32, Int64, System.Object, System.String, System.Object[])
DEBUG|WampSharp.Core.Proxy.WampOutgoingRequestSerializer`1[Newtonsoft.Json.Linq.JToken]|Calling remote peer proxy method: Void Error(Int32, Int64, System.Object, System.String, System.Object[])
DEBUG|WampSharp.Msgpack.MessagePackParser|Formatting message: "[8,48,1026659629621231,{},"wamp.error.invalid_argument",["argument position: 0"]]"
...
```

My problem:
The log is not giving me enough information. When I look at the arguments `["*",3]` everything looks alright to me - a string and a number (enum) - exactly what the procedure expects. It would be nice if WampSharp could tell me, why it does not like those arguments.

Thanks
Esso

**Comment by darkl** [comment]
1. Can't reproduce. See [here](https://gist.github.com/darkl/0d2cca84124fb2ffbaaef25fc59e13f9). Since the log complains about argument zero, I guess that your method signatures are mismatched (probably one of them expects a string as the first argument and the other expects an enum as the first argument).
2. The exception `An error occured while calling "sk.ipecon.development.d2client.publish_multiple_d2_objects"` contains an inner exception which contains information regarding the problematic argument (i.e. its position or name). That inner exception in turn contains another inner exception which contains the deserialization error. Your logging framework should be able to leverage this data.

**Comment by esso23** [comment]
This is how the log looks like with printed InnerExceptions.
```
2018-08-08 12:49:14.1247|ERROR|WampSharp.V2.Rpc.LocalRpcOperation.sk.ipecon.development.d2client.publish_multiple_d2_objects|An error occured while calling "sk.ipecon.development.d2client.publish_multiple_d2_objects"|EXCEPTION OCCURRED:WampSharp.V2.Core.Contracts.WampInvalidArgumentException Unable to deserialize a given argument. argument position: 0 System.Object GetPositionalParameterValue[TMessage](WampSharp.Core.Serialization.IWampFormatter`1[TMessage], WampSharp.V2.Core.LocalParameter, TMessage)
TargetInvocationException Exception has been thrown by the target of an invocation. System.Object InvokeMethod(System.Object, System.Object[], System.Signature, Boolean)
InvalidCastException Unable to cast object of type 'Newtonsoft.Json.Linq.JValue' to type 'System.String'. TTarget Deserialize[TTarget](System.Object)
```
The problem is that I don't know what Newtonsoft.Json.Linq.JValue contains from this log entry.

Both clients are referencing the same assembly with callee interface contracts so there is no way the parameters are mispositioned since there is only one callee interface definition.

I tried calling this with InMemoryTransport and everything works fine, it is only when I connect remote client I start seeing some weird errors like this. (I have others, like client calling proxy method, router sending proper answer but client never receiving it and thus freezing).

**Comment by esso23** [comment]
This is where the error occurs. It jums to the method above and then fails the cast.

![screenshot 2018-08-08 13 56 53](https://user-images.githubusercontent.com/5548662/43835900-d38105c6-9b13-11e8-8d64-553110eda396.png)

**Comment by darkl** [comment]
Why don't you attach a repro so I can investigate this (otherwise it would be a shoot in the dark).

**Comment by esso23** [comment]
I tried, but so far I was unsuccessful in reproducing it. It may take a lot of time (hope I won't end up copying the whole solution into repro...), so I tried to take a shortcut...

**Comment by darkl** [comment]
I suspect that the problem lies in the way you initiate the InMemoryTransport and the in-memory clients.

**Comment by esso23** [comment]
OK wow, I guess I "fixed" it. But it makes no sense to me to be honest.
So here's my router: https://gist.github.com/esso23/497ed2d5c9cadce7729cc46853a30dba
I removed stuff that's not relevant like logging and configuration.

This is the important line:
https://gist.github.com/esso23/497ed2d5c9cadce7729cc46853a30dba#file-router-cs-L58

I used to have just InMemoryBinding there. Also when creating channel I called GetChannel method like this:
```cs
Router.Value.GetChannel(new InMemoryBinding())
```
Now I call it like this:
```cs
Router.Value.GetChannel(new JTokenJsonBinding())
```
And that fixed the problem.
So my first question is, why did it even work? And why do I need to use JTokens in memory?
And also, why it messed with clients which don't use InMemoryTransport? MsgPack and Json transports are registered in DefaultWampClient so they should be totally independent from this and should continue working normally, or am I wrong?

**Comment by darkl** [comment]
This is a long story. WAMP clients communicate via objects that are called WAMP messages. These are basically arrays that contain the WAMP message type and the message arguments. These WAMP messages can be represented in various ways: as JSON strings, MsgPack bytes or as instances of the WampMessage class in WampSharp. Whenever a WAMP message is sent/received, WampSharp creates a WampMessage object representing it.

Usually the work does not end there, as the user might want to deserialize the JSON payload into a custom object. So a WAMP message received from the wire is deserialized to a WampMessage with generic type JToken, which allows each argument to be deserialized further to a custom type.

The InMemoryBinding is intended for peers living in the same process, and therefore no serialization or deserialization of the arguments happens when one uses this binding. Instead casts are used.

When you mix the InMemoryBinding with a remote client, it will receive a WampMessage with object type JToken. By default it will assume that the message is received from a peer in the same process, and therefore will simply try to cast the arguments to the user's custom objects. As you saw already, this fails.

In order to avoid this problem, we need to tell the InMemoryBinding about the wire serializers. The way to do this is to call the AddFormatter method of the InMemoryBinding instance. This will make the InMemoryBinding first try to look for a JToken formatter, and only then fallback to the default behavior of using casts.

Example
```csharp
WampHost host = new WampHost();

JTokenJsonBinding jsonBinding = new JTokenJsonBinding();
JTokenMsgpackBinding messagePackBinding = new JTokenMsgpackBinding();

host.RegisterTransport(new FleckWebSocketTransport("ws://127.0.0.1:8080/ws/"),
                       jsonBinding,
                       messagePackBinding);

InMemoryBinding memoryBinding = new InMemoryBinding();
memoryBinding.AddFormatter(jsonBinding.Formatter);

InMemoryTransport memoryTransport = new InMemoryTransport(ImmediateScheduler.Instance);

host.RegisterTransport(memoryTransport, new IWampBinding[] { memoryBinding });

host.Open();
```

Then using the same instance InMemoryBinding instance and the same InMemoryTransport we can obtain our WampChannel

```csharp
WampChannelFactory factory = new WampChannelFactory();

IWampChannel channel =
    factory.CreateChannel("realm1",
                          memoryTransport
                              .CreateClientConnection(memoryBinding,
                                                      ImmediateScheduler.Instance),
                          memoryBinding);

await channel.Open().ConfigureAwait(false);

await channel.RealmProxy.Services.RegisterCallee(new Test()).ConfigureAwait(false);
```

Another option which is the one that you explored: one can register a JTokenJsonBinding with the InMemoryTransport and use it for the clients. This will work, but will cause all WAMP messages to be serialized/deserialized to/from JToken, even when the peers live in the same process.

Why isn't this done automatically? The InMemoryBinding isn't aware of the registered bindings of the WampHost. In fact it should not be aware of these, as it is intended for the in-memory serialization method, which means that either types are compatible or not.

Elad

**Comment by esso23** [comment]
Thanks a for for explaining this to me. Much appreciated.
