### ISSUE TITLE
Intercepting RPC calls on Callee

### ISSUE THREAD

**Issue by esso23** [Code-Sharp/WampSharp#278]
Hi Elad,
I'm using reflection-based callee with like 50 RPCs. Everytime an RPC is callled I want to perform an action that is the same for all RPCs - like log the name of the RPC and its parameters. I would also like to measure the time of execution for each one of them etc. etc. Currently the best way to do this (as far as I know) is to use `WampInvocationContext`, but this forces me to make lots of duplicate code, as I need to call the same methods in every RPC implementation.
I was thinking it would be ideal if I could intercept the call and response to every RPC on the client and perform those actions there. Is there a way to do this right now? If not, would it be possible to implement something like this?

Thanks
Esso

**Comment by darkl** [comment]
Use Castle.Core or another interception framework directly to wrap your objects with your desired logic. Passed the wrapped objects to RegisterCallee.

See also #157.

Elad

**Comment by esso23** [comment]
Thanks Elad, I never worked with Castle before so I don't know what it can do.

Here's a simple way of doing this for those in need ;)

Interceptor:
```cs
    public class RpcInterceptor : IInterceptor
    {
        private static readonly Logger Logger = LogManager.GetCurrentClassLogger();

        public void Intercept(IInvocation invocation)
        {
            Logger.Info($"Intercepted invocation of {invocation.Method.Name}.");
            invocation.Proceed();
            Logger.Info($"Call to {invocation.Method.Name} finished.");
        }
    }
```

Proxy registration:
```cs
    ICallee calleeInterface = new Callee();
    ProxyGenerator generator = new ProxyGenerator();
    mCallee = generator.CreateInterfaceProxyWithTarget(
            calleeInterface,
            ProxyGenerationOptions.Default,
            new RpcInterceptor());
    mRegistration = await RealmProxy.Services.RegisterCallee(mCallee);
```

**Comment by StevenBonePgh** [comment]
Be careful with async callee implementations, as the first await is likely to cause `invocation.Proceed()` to return, which will not give you the metrics you are looking for.  Also beware that sync implementations of callees (and anything prior to the first await in an async implementation) will block the websocket and prevent other calls from other clients being run simultaneously so any non-trivial callees are best implemented async.  

A hint for handling async interception properly is to do something like this after `invocation.Proceed();` (NOTE: will not work for async void, but there is no reason to use async void in a WAMPSharp callee):
`var returnsTaskType = typeof(Task).IsAssignableFrom(invocation.MethodInvocationTarget?.ReturnType ?? typeof(object));`

If `returnsTaskType` is true, then do this (do not await it):
 `invocation.ReturnValue = InterceptAsync((dynamic)invocation.ReturnValue);`

The implementation for the two necessary `InterceptAsync` methods look like:
```
private async Task<T> InterceptAsync<T>(Task<T> task)
{ return await task.ConfigureAwait(false); }
private async Task InterceptAsync(Task task)
{ return await task.ConfigureAwait(false); }
```
You probably want to wrap the `invocation.Proceed()` and the body of the `InterceptAsync` methods to log exceptions. I use `dynamic` here because the compiler/runtime can do all the hard work for me better than I could. I use this technique not only for metrics, but for populating a `ThreadLocal<T>` in the implementing type with an object that I create from `WampInvocationContext.Current` so I have some necessary details related to the client that I can check first thing in the implementation of the callee.

@darkl : Thoughts on this approach? Perhaps adding something like this to a FAQ section in the doc site?

**Comment by darkl** [comment]
I implemented in the past an interception framework over WCF, using Castle. It was before framework 4.5, so we had to use the BeginXXX/EndXXX syntax. Anyway, we quite quickly had to introduce the notion of an IAsyncInterceptor, which I guess is similar to your Task interceptor. It wasn't easy to implement all concerns. We basically had a logging interceptor, a statistics interceptor (which tracked how many times each rpc is called, and how long does the average call take), and maybe a few others.

I might include some built-in mechanism like this in a future WampSharp version, but I doubt I'll be able to do a better job than Castle.Core and Interception libraries.

For the meanwhile, you guys are certainly welcome to open pull requests to the WampSharp.net repository with useful best practices.
