### ISSUE TITLE
Modify WampTopics at Runtime?

### ISSUE THREAD

**Issue by bradws** [Code-Sharp/WampSharp#337]
Hi,

I have a conceptual client/server arcitecture where there will be many client apps, and one server app. This works just fine.
However if spawning a 2nd server, the batch of clients interacting with the Server1 instance, will get confused with the Server2 instance (won't it?).

My initial thoughts were to modify the `WampTopic` values at run-time by pre-appending them with a unique ID before registering. That way, when the Server2 instance spawns up, all the events/rpcs will be unique to the clients that specifically 'connect' to the Server2. However after investigation, I can see the `TopicUri` property is get-only, and also the `WampTopic` does not inherrit from the standard .NET `Attribute` class at all.

Maybe when spawning Server2, it connects to a different `Realm`, but im not sure how to dynamically make a Realm on the router, and then notify the Server2 and related clients the Realm name.

I'm using the C# [WampSharp](https://wampsharp.net/) library, so I do have some control over the Router.

Can anyone suggest a solution to this?

**Comment by darkl** [comment]
I'm not sure I understand the question. You have two server apps publishing to the same topic uri but they should not because clients expect to receive only the events published by one of the servers? Then maybe you should make each server publish to its own topic uri. If the problem is that these are two instances of the same application, you will have to introduce some configuration value that tells the app which instance is it and append this value to the topic uris. You can use interceptors in order to change the topic uri at runtime for reflection-based Publisher/Subscriber.

**Comment by bradws** [comment]
Thank-you, yes you're right. There will be >1 instances of the same server application.
In the example [Call Customization](https://wampsharp.net/wamp2/roles/caller/reflection-based-caller/) section, it looks like Interceptors are what I'm looking for. 👍 

The example here shows the use of a proxy with RPCs [WampProcedure], but what about Pub/Sub [WampTopic]? You mention that you can, but the example library's CalleeProxyInterceptor class only seems to have a  GetProcedureUri(MethodInfo method) and nothing for the Pub/Sub ?  How can I get at the uri's for Pub/Sub ?

**Comment by darkl** [comment]
Check out the interfaces `ISubscriberRegistrationInterceptor`, `IPublisherRegistrationInterceptor`, `ICalleeProxyInterceptor`, `ICalleeRegistrationInterceptor`. The realm service provider provides overloads for each of these.

**Comment by bradws** [comment]
Thanks - this was exactly what I was looking for.
