### ISSUE TITLE
wamp connection broken error on rpc called from inside subscribe action 

### ISSUE THREAD

**Issue by gtaranas** [Code-Sharp/WampSharp#59]
Hi,

i m trying to make something like that

IDisposable subscription = subject.Subscribe(message =>
{
 rpcCallHere()
})

and i am getting a connection broker error after 10 sec

any ideas please?

**Comment by darkl** [comment]
Hi @gtaranas,

Is your rpc call in the subscribe synchronous or asynchronous?
If synchronous, its blocking and then the WebSocket connection can't receive messages (since its thread raised the subscriber's on next message). You can solve this in a couple of ways:
* Keep the call synchronous, but schedule it on a different thread (using subject.ObserveOn(), for example, subject.ObserveOn(new NewThreadScheduler()).Subscribe(...)
* Use an asynchronous call instead, then you can use rx to compose the calls and events:
IObservable&lt;MyResult&gt; observable =
from message in subject
from result in rpcCallHere(message)
select result;

**Comment by gtaranas** [comment]
Thanks for your quick response, i will try it.
