### ISSUE TITLE
Cannot Override JsonSerializer ContractResolver in JsonFormatter

### ISSUE THREAD

**Issue by shanielh** [Code-Sharp/WampSharp#82]
Look at line 21 in [JsonFormatter.cs](https://github.com/Code-Sharp/WampSharp/blob/wampv2/src/net45/WampSharp.Default/Newtonsoft/JsonFormatter.cs).

This line is overriding my JsonResolver, Can I rewrite it as decorator?

**Comment by wamp-implementations** [comment]
Hi,

DefaultJsonContractResolver is not composable (It consists of protected
methods instead of an interface).

Anyways, I already got rid of my ContractResolver in the develop branch.
Please reference develop branch dlls via MyGet feed
<https://www.myget.org/feed/Packages/wampsharp>. This will be available on
NuGet on next release.

**Comment by darkl** [comment]
Hi,

DefaultJsonContractResolver is not composable (It consists of protected methods instead of an interface).

Anyways, I already got rid of my ContractResolver in the develop branch. Please reference develop branch dlls via [MyGet feed](https://www.myget.org/feed/Packages/wampsharp). This will be available on NuGet on next release.

**Comment by shanielh** [comment]
Thank you. Waiting for the next release :smile:
