### ISSUE TITLE
WampSharp.V1.DefaultWampChannelFactory overload does not set the JsonSerializer, exception during WebSocket4Net Send() exception causes client to block forever.

### ISSUE THREAD

**Issue by StevenBonePgh** [Code-Sharp/WampSharp#95]
Hi Elad,

I'm updating from 1.2.0.0-beta to the current version of the library.  Great work in minimizing the pain of this migration - and I like the new organization!  This report is likely two distinct issues, if you wish me to split them, I can, but it is easiest to reproduce the second issue with the first issue.  The second issue was discovered first... 

The first issue is the overload WampSharp.V1.DefaultWampChannelFactory.DefaultWampChannelFactory(IWampFormatter<JToken> formatter) does not set mSerializer.  If this overload is used, it will create a NullReferenceException in WampSharp.Newtonsoft.JTokenMessageParser.Format(WampMessage<object> message), as the ctor for JTokenMessageParser will be passed a null JsonSerializer.  That overload should likely also accept the serializer.  In my case, I need to use a serializer with some tweaks.

The second issue is a bit more disturbing due to the behavior that occurs when Send() fails (at least when using WebSocket4Net).  An RPC call made on the proxy will never return nor throw an exception to the caller when Send() fails.  Ultimately, WampSharp.WebSocket4Net.WebSocket4NetConnection<TMessage>.IWampConnection<TMessage>.Send(WampMessage<object> message) eats (and does not log) the exception, which means the calling client is now blocked forever waiting for a response.

Thanks,
Steve

**Comment by darkl** [comment]
Hi Steve,
Nice to see you again :)

I don't have much time in the next few weeks to work on this project, but I'll try to give you some hints so you won't be stuck.

About the first issue - it seems that I accidentally left that overload public (instead of making it private). Actually users shouldn't call it and should call the overload that gets the JsonSerializer if they want to customize JSON serialization - will that work for you?

About the second issue - the WebSocket4Net semantics are that errors are reported to an event handler named Error, so Send shouldn't actually throw an exception. (actually WebSocket4Net enqueues messages and sends them asynchronously and serially, so the exception shouldn't occur on Send call, but later and should be reported to the Error handler)
I agree it is not nice that the current implementation eats the exception that should never occur, maybe this should be removed or least logged and forwarded to ConnectionError.

I'm not sure if the WAMPv1 implementation listens to the WampClientConnectionMonitor events and sets exceptions for pending rpc calls (WAMPv2 implementation does this), but if it doesn't then I'm not sure I'll add something like this, since WAMPv1 is considered obsolete now, and I'm not interested in working on it (unless the issue is simple and has a simple fix).

**Comment by StevenBonePgh** [comment]
Nice to talk to you again, also :)

On the first issue, the correct solution is as you proposed.  1.2.0.0-beta had it public, likely as a result of a previous request of mine so I could pass some unique serialization settings, as the other constructors did not exist at the time.  Making that one private appears to be the correct fix.

On issue 2, The error in send occurred during serialization, before it made it to WebSocket4Net queue, so even if V1 canceled pending RPC calls on a connection error (which it does not appear to do), it would still block the caller.  Doing a brief test of not catching the exception in Send() appears to function as expected - the RPC caller gets the exception reported to it. 

On issue 2a, I like what you did with this in v2.  I understand you don't want to do it in v1, but I'll need to support v1 for a bit until clients can move to v2.  1.2.0.0-beta has the same flaw - a connection error does not cancel the RPC.  Pull request on the way for this in v1.

Thanks!

Steve
