### ISSUE TITLE
wamp.error.invalid_topic

### ISSUE THREAD

**Issue by devfxplayer** [Code-Sharp/WampSharp#99]
WampSharp.V2.Core.Contracts.WampException: Error uri: 'wamp.error.invalid_topic', details: topicUri: com.myapp.topic1
   at WampSharp.V2.PubSub.WampTopicContainer.InnerPublish(Func`3 publishAction, String topicUri)

Please help

**Comment by darkl** [comment]
Hi @devfxplayer, please add more information about what you are trying to do. A code snippet can be useful.

**Comment by devfxplayer** [comment]
const string serverAddress = "ws://127.0.0.1:8080/ws";
            DefaultWampHost h = new DefaultWampHost(serverAddress);
            h.Open();
            IWampHostedRealm r = h.RealmContainer.GetRealmByName("realm1");            
            ISubject<string> subject =
                r.Services.GetSubject<string>("com.myapp.topic1");
 subject.OnNext("test");   //here i get the error

**Comment by darkl** [comment]
It is an inner exception that is caught by the library, it should not crash your application.
It occurs because no one is subscribed to the topic. You can avoid it if you want to by creating that topic: 

```csharp
realm.TopicContainer.CreateTopicByUri("com.myapp.topic1", true);
```

But it is also ok to ignore this exception, you should not see it if you are not catching in Visual Studio user handled exceptions.

**Comment by devfxplayer** [comment]
thank you
